"""add provider_uuid loose relationship to stock

Revision ID: b610ca0c4817
Revises: 9dd152edd913
Create Date: 2021-06-30 17:18:56.012609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b610ca0c4817'
down_revision = '9dd152edd913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('provider_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'provider_uuid')
    # ### end Alembic commands ###
